# Generated by Django 5.2.13 on 2026-06-06 01:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scores', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='students.student'),
        ),
        migrations.AlterUniqueTogether(
            name='score',
            unique_together={('student', 'course', 'semester')},
        ),
    ]
