# Generated by Django 5.2.13 on 2026-06-06 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_semester'),
        ('scores', '0002_initial'),
        ('students', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='score',
            unique_together={('student', 'course')},
        ),
        migrations.RemoveField(
            model_name='score',
            name='semester',
        ),
    ]
