# Generated by Django 5.2.13 on 2026-06-06 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.CharField(default='2025-2026-1', max_length=20, verbose_name='学期'),
        ),
    ]
