# Generated by Django 5.2.13 on 2026-06-06 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='班级名称')),
                ('grade', models.CharField(max_length=20, verbose_name='年级')),
                ('major', models.CharField(max_length=50, verbose_name='专业')),
                ('student_count', models.IntegerField(default=0, verbose_name='学生人数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '班级',
                'verbose_name_plural': '班级',
                'db_table': 'classes',
                'ordering': ['-created_at'],
            },
        ),
    ]
