# Generated by Django 5.2.13 on 2026-06-06 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InfoChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=50, verbose_name='修改字段')),
                ('old_value', models.CharField(max_length=200, verbose_name='原值')),
                ('new_value', models.CharField(max_length=200, verbose_name='新值')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('rejected', '已驳回')], default='pending', max_length=10, verbose_name='状态')),
                ('review_time', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('remark', models.CharField(blank=True, default='', max_length=200, verbose_name='审核备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='申请时间')),
            ],
            options={
                'verbose_name': '信息变更申请',
                'verbose_name_plural': '信息变更申请',
                'db_table': 'info_change_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_no', models.CharField(max_length=20, unique=True, verbose_name='学号')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女')], max_length=6, verbose_name='性别')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='年龄')),
                ('phone', models.CharField(blank=True, default='', max_length=20, verbose_name='联系电话')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='邮箱')),
                ('address', models.CharField(blank=True, default='', max_length=200, verbose_name='家庭地址')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='头像')),
                ('status', models.CharField(choices=[('normal', '正常'), ('pending', '待审核')], default='normal', max_length=10, verbose_name='状态')),
            ],
            options={
                'verbose_name': '学生',
                'verbose_name_plural': '学生',
                'db_table': 'students',
            },
        ),
    ]
